sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t amarbelkhede/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amarbelkhede/react-test npm test

after_success:
  - docker build -t amarbelkhede/multi-client ./client
  - docker build -t amarbelkhede/multi-nginx ./nginx
  - docker build -t amarbelkhede/multi-server ./server
  - docker build -t amarbelkhede/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push amarbelkhede/multi-client
  - docker push amarbelkhede/multi-nginx
  - docker push amarbelkhede/multi-server
  - docker push amarbelkhede/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-558402650035
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
